
export default  [
                 'Acura',
                 'Alfa Romeo',
                 'Aston Martin',
                 'Audi',
                 'Bentley',
                 'BMW',
                 'Bugatti',
                 'Buick',
                 'Cadilac',
                 'Chevrolet',
                 'Chrysler',
                 'Citroen',
                 'Dodge',
                 'Ferrari',
                 'Fait',
                 'Ford',
                 'Geely',
                 'GM',
                 'GMC',
                 'Honda',
                 'Hyundai',
                 'Infiniti',
                 'Jaguar',
                 'Jeep',
                 'Kia',
                 'Koenigsegg',
                 'Lamborghini',
                 'Land Rover',
                 'Lexus',
                 'Maserati',
                 'Mazda',
                 'McLaren',
                 'Mercedes-Benz',
                 'Mini',
                 'Pagani',
                 'Peugeot',
                 'Porsche',
                 'Ram',
                 'Renault',
                 'Rolls Royce',
                 'Saab',
                 'Subaru',
                 'Suzuki',
                 'Tata Motors',
                 'Tesla',
                 'Toyota',
                 'Volkswagen',
                 'Volvo',
                 'Jaguar'
                 ] 
