export default [
                '3000ME',
                'Shelby Cobra',
                'Frua',
                '75',
                '33',
                '33 Stradale',
                '155',
                '156',
                'Alfasud',
                'Arna',
                'Brera',
                'GT',
                'Montreal',
                'Spider',
                'SZ',
                'RZ',
                'A106',
                'A108/Willys Interlagos',
                'A110',
                'A310',
                'GTA/A610',
                'Gremlin',
                'Hornet',
                '80',
                '90',
                'Coupé/Quattro',
                'A1',
                'A3',
                'A4',
                'A5',
                'A6',
                'A7',
                'A8',
                'R8',
                '326',
                '327',
                '328',
                '503',
                '507',
                '3200 cs',
                'New Class',
                '2000C',
                '2000CS',
                'CS',
                'i3',
                'i8',
                'M1',
                'M8',
                'Z1',
                'Z8',
                '3 Series',
                '5 Series',
                '8 Series',
                'X5',
                'Type 18',
                'Type 30',
                'Type 35',
                'Type 37',
                'Type 38',
                'Type 39',
                'Type 40',
                'Type 41',
                'Type 50',
                'Type 51',
                'Type 55',
                'Type 57',
                'Type 101',
                'EB110',
                'Veyron',
                'Chiron',
                'Riviera',
                'Allanté',
                'De Ville',
                'ELR',
                'XTS',
                'ATS',
                'CTSV',
                'Camaro',
                'Caprice',
                'Corvette',
                'Impala',
                '300',
                '300s',
                'Pantera',
                'Viper',
                'Charger',
                'Challenger',
                'Dart',
                '166 MM',
                '212 Inter',
                '250 GT Coupé',
                '250 GT Berlinetta "Tour de France"',
                '250 GT Berlinetta SWB',
                '250 GTO',
                '250 GT Lusso',
                '275',
                '250 LM',
                'Dino',
                '365 GTB',
                '365 GTS',
                '512S',
                '512M',
                'BB',
                '308 GTB',
                '308 GTS',
                'Mondial',
                'Testarossa',
                '288 GTO',
                'F40',
                '348',
                '456',
                '333 SP',
                'F355',
                'F50',
                '550 Maranello',
                '575M Maranello',
                '360',
                'Enzo',
                'F430',
                'FF',
                'LaFerrari',
                'Crown Victoria',
                'Explorer',
                'F-Series',
                'Falcon',
                'Fiesta',
                'Focus',
                'GT',
                'Model A',
                'Model T',
                'Mustabg',
                'Ranger',
                'RS200',
                'Tempo',
                'Thunderbird',
                'Accord',
                'Beat',
                'Civic',
                'CR-V',
                'Fit',
                'NSX',
                'S500',
                'S600',
                'S800',
                'S2000',
                'XK120',
                'C-Type',
                'D-Type',
                'E-Type',
                'Mark 1',
                'XJ220',
                'XK',
                'X-Type',
                'XF',
                'Cherokee',
                'XJ',
                'CJ',
                'Wrangler',
                'Renegade',
                'Aventador',
                'Countach',
                'Diablo',
                'Espada',
                'Gallardo',
                'Huracán',
                'Miura',
                'Murciélago	',
                'Reventón',
                'Defender',
                'Evoque',
                'Velar',
                'Sport',
                'autobiography',
                'LFA',
                'Elise',
                'F1',
                'P1',
                '12C',
                '540C',
                '570s',
                '675',
                '675 LT',
                '650s',
                '720s',
                'Speedtail',
                'GT',
                'Elva',
                '600LT',
                'SENNA',
                'SENNA GTR',
                'MC12',
                'GrandTurismo',
                'RX-8',
                'SLR',
                'SL',
                'SLS',
                'AMG',
                'r32',
                'r34',
                'r35',
                'FairLady Z',
                'P50',
                'Firebird',
                '911',
                '918',
                '904',
                '550',
                '356',
                '906',
                '908',
                '914',
                '917',
                '956',
                '962',
                '959',
                '968',
                'Boxter',
                'Cayenne',
                'Carrera GT',
                'Panamera',
                'Macan',
                'S7',
                'Model S',
                'Model 3',
                'Model X',
                'Model Y',
                'Roadster',
                '2000GT',
                'Supra',
                'S40',
                'S90'
            ]